name: Deploy LW Container Scanner

on:
  push:
    branches: [ master ]

env:
  ECR_REPOSITORY: python-docker
  EKS_CLUSTER_NAME: bj-eksprod-1 
  AWS_REGION: ap-south-2

jobs:
  scanning:
    name: Container Vuln Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Scan container image for vulnerabitilies using Lacework
        uses: lacework/lw-scanner-action@v1.4.0
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ env.GHA_SHA }}
          SAVE_RESULTS_IN_LACEWORK: true
          RESULTS_IN_GITHUB_SUMMARY: true

      - name: Change formatting for PR
        run: |
            echo "# Lacework Inline Scanner Result" > pr-results.md
            echo "<pre>" >> pr-results.md
            cat results.stdout >> pr-results.md
            echo "</pre>" >> pr-results.md

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr-results.md
